name: CD - Despliegue automatico a EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build, scan, push y deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build de la imagen
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/devops-api:latest .

      - name: Escaneo DevSecOps con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/devops-api:latest
          severity: 'CRITICAL'
          exit-code: '1'
          ignore-unfixed: true
          trivyignores: .trivyignore

      - name: Push a ECR (solo si pasa el scan)
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/devops-api:latest

      - name: Desplegar en EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 416045273826.dkr.ecr.us-east-1.amazonaws.com
            docker pull 416045273826.dkr.ecr.us-east-1.amazonaws.com/devops-api:latest
            docker stop api-devops || true
            docker rm api-devops || true
            docker run -d -p 8000:8000 --name api-devops --restart unless-stopped 416045273826.dkr.ecr.us-east-1.amazonaws.com/devops-api:latest
            docker image prune -f